{{- if and (has "dep_ingresses" .Values.enabled_apps) (.Values.dep_ingresses.storm.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.dep_ingresses.name }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- if .Values.certmanager.enabled }}
    cert-manager.io/issuer: ca-issuer
  {{- end }}
  {{- if .Values.dep_ingresses.storm.oauth2_proxy.enabled }}
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.dep_ingresses.storm.oauth2_proxy.host }}/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Values.dep_ingresses.storm.oauth2_proxy.host }}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
  {{- end }}
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.dep_ingresses.storm.fqdn }}
    secretName: {{ .Values.dep_ingresses.name }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.dep_ingresses.storm.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ .Values.dep_ingresses.storm.service.name }}
            port: 
              number:  {{ .Values.dep_ingresses.storm.service.port }}
{{- end -}}