apiVersion: batch/v1
kind: Job
metadata:
  name: --name--
  namespace: --namespace--
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - env:
            - name: NIMBUS_SEEDS
              value: '--nimbus--'
          args: --args--
          image: --image--
          name: --name--
      securityContext:
        runAsUser: 101
